services:
  tcc-cola-back:
    build: ./backend
    container_name: tcc-cola-back
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: tcc-cola-back
      SERVICE_TAGS: dev
      DB_HOST: db-tcc-cola
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www/tcc-cola
    volumes:
      - ./backend:/var/www/tcc-cola
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tcc-cola-network
    depends_on:
      - db-tcc-cola
    ports:
      - "9000:9000"
  db-tcc-cola:
    container_name: tcc-cola
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tcc-cola-network

  adminer:
    container_name: adminer-tcc-cola
    image: adminer
    restart: always
    ports:
      - "8089:8080"
    networks:
      - tcc-cola-network
    depends_on:
      - db-tcc-cola

networks:
  tcc-cola-network:
    driver: bridge

volumes:
  dbdata:
    driver: local